// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ8wR_CAJ8XoYno44Q98PBeBbNHKG_M14',
    appId: '1:391620850275:web:d265d5c039ae6bd9b87e56',
    messagingSenderId: '391620850275',
    projectId: 'notes-37979',
    authDomain: 'notes-37979.firebaseapp.com',
    storageBucket: 'notes-37979.appspot.com',
    measurementId: 'G-WQ4F00HPQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ-xLPKRyFvkDM7fBP_svnPfkul0mBvQs',
    appId: '1:391620850275:android:5b72bf2167f78c7db87e56',
    messagingSenderId: '391620850275',
    projectId: 'notes-37979',
    storageBucket: 'notes-37979.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuSXNHr9kmlO9dlBeJG_0xQ3TzllwObuQ',
    appId: '1:391620850275:ios:bcce727aced11dabb87e56',
    messagingSenderId: '391620850275',
    projectId: 'notes-37979',
    storageBucket: 'notes-37979.appspot.com',
    iosBundleId: 'com.example.youtubePlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuSXNHr9kmlO9dlBeJG_0xQ3TzllwObuQ',
    appId: '1:391620850275:ios:35ced902182d5af9b87e56',
    messagingSenderId: '391620850275',
    projectId: 'notes-37979',
    storageBucket: 'notes-37979.appspot.com',
    iosBundleId: 'com.example.youtubePlayer.RunnerTests',
  );
}
